// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_exn from "../../node_modules/bs-platform/lib/es6/js_exn.js";
import * as Js_json from "../../node_modules/bs-platform/lib/es6/js_json.js";
import * as ReasonReact from "../../node_modules/reason-react/src/ReasonReact.js";
import * as Gatsby$ReactTemplate from "../Gatsby.js";

var component = ReasonReact.statelessComponent("Title");

var ppx_printed_query = "query IndexQuery  {\nsite  {\nsiteMetadata  {\ntitle  \n}\n}\n}";

function parse(value) {
  var match = Js_json.decodeObject(value);
  if (match) {
    var match$1 = match[0]["site"];
    var tmp;
    if (match$1 !== undefined) {
      var match$2 = Js_json.decodeNull(match$1);
      if (match$2) {
        tmp = /* None */0;
      } else {
        var match$3 = Js_json.decodeObject(match$1);
        var tmp$1;
        if (match$3) {
          var match$4 = match$3[0]["siteMetadata"];
          var tmp$2;
          if (match$4 !== undefined) {
            var match$5 = Js_json.decodeNull(match$4);
            if (match$5) {
              tmp$2 = /* None */0;
            } else {
              var match$6 = Js_json.decodeObject(match$4);
              var tmp$3;
              if (match$6) {
                var match$7 = match$6[0]["title"];
                var tmp$4;
                if (match$7 !== undefined) {
                  var match$8 = Js_json.decodeNull(match$7);
                  if (match$8) {
                    tmp$4 = /* None */0;
                  } else {
                    var match$9 = Js_json.decodeString(match$7);
                    tmp$4 = /* Some */[match$9 ? match$9[0] : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(match$7))];
                  }
                } else {
                  tmp$4 = /* None */0;
                }
                tmp$3 = {
                  title: tmp$4
                };
              } else {
                tmp$3 = Js_exn.raiseError("graphql_ppx: Object is not a value");
              }
              tmp$2 = /* Some */[tmp$3];
            }
          } else {
            tmp$2 = /* None */0;
          }
          tmp$1 = {
            siteMetadata: tmp$2
          };
        } else {
          tmp$1 = Js_exn.raiseError("graphql_ppx: Object is not a value");
        }
        tmp = /* Some */[tmp$1];
      }
    } else {
      tmp = /* None */0;
    }
    return {
            site: tmp
          };
  } else {
    return Js_exn.raiseError("graphql_ppx: Object is not a value");
  }
}

function make() {
  return {
          query: ppx_printed_query,
          variables: null,
          parse: parse
        };
}

function makeWithVariables() {
  return {
          query: ppx_printed_query,
          variables: null,
          parse: parse
        };
}

function ret_type() {
  return /* module */[];
}

var MT_Ret = /* module */[];

var Query = /* module */[
  /* ppx_printed_query */ppx_printed_query,
  /* query */ppx_printed_query,
  /* parse */parse,
  /* make */make,
  /* makeWithVariables */makeWithVariables,
  /* ret_type */ret_type,
  /* MT_Ret */MT_Ret
];

function make$1() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(/* None */0, /* None */0, Gatsby$ReactTemplate.StaticQuery[/* make */0](make(/* () */0).query, (function (data, _) {
                                var title = data.site.siteMetadata.title;
                                return React.createElement("div", undefined, title);
                              }), /* array */[]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  component ,
  Query ,
  make$1 as make,
  
}
/* component Not a pure module */
