// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Gatsby from "gatsby";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as GatsbyLink from "gatsby-link";

function make(query, render, children) {
  return ReasonReact.wrapJsForReason(Gatsby.StaticQuery, {
              query: query,
              render: render
            }, children);
}

var StaticQuery = /* module */[/* make */make];

function make$1(_to, children) {
  return ReasonReact.wrapJsForReason(GatsbyLink.default, {
              to: _to
            }, children);
}

var Link = /* module */[/* make */make$1];

export {
  StaticQuery ,
  Link ,
  
}
/* gatsby Not a pure module */
