// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var Graphql = /* module */[];

var BoundActionCreators = /* module */[];

var query = "\n   {\n     events: allFile {\n       edges {\n         node {\n           absolutePath\n             childEventsYaml {\n               type\n             }\n         }\n       }\n     }\n   } ";

function createPages(args) {
  var gql = args.graphql;
  var actions = args.boundActionCreators;
  console.log("Actions: ", actions);
  return gql(query).then((function (r) {
                var eventFiles = r.data.events.edges;
                console.log("event files: ", eventFiles);
                return Promise.resolve("Yo");
              }));
}

exports.Graphql = Graphql;
exports.BoundActionCreators = BoundActionCreators;
exports.query = query;
exports.createPages = createPages;
/* No side effect */
